server {
    listen 0.0.0.0:80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Gzip-Komprimierung aktivieren
    gzip on;
    gzip_static on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/font-woff application/octet-stream;
    gzip_min_length 1000;
    gzip_vary on;

    # Cache für statische Assets aktivieren
    location ~* \.(?:js|css|woff2?|ttf|eot|ico|svg|jpg|jpeg|png|gif|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    # SPA-Routing – React/Vite-Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
