/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useEffect, useRef, useState } from "react";


import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    friendlyMouth: 1,
    friendlyRightEye: 1,
    friendlyLeftEye: 1,
    friendlyRightEyebrow: 1,
    friendlyLeftEyebrow: 1,
  },

};

const lipsyncDefinition = {
  A: "A",
  B: "B",
  C: "C",
  D: "D",
  E: "E",
  F: "F",
  G: "A",
  H: "A",
  X: "X"
};

export function Avatar(props) {
  const group = useRef();

  const { nodes, materials, scene, animations } = useGLTF(
    "/models/talkywalky.glb"
  );
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "idle") ? "idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );
  const { message, onMessagePlayed, chat } = useChat();
  const [lipsync, setLipsync] = useState();
  const [blink, setBlink] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();


  useEffect(() => {
    console.log(message);

    if (!message) {
      setAnimation("idle");
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);

    setLipsync(message.lipsync);
    const audio = new Audio("data:audio/mp3;base64," + message.audio);
    console.log("audio:" + audio);
    audio.play();
    setAudio(audio);
    audio.onended = onMessagePlayed;
  }, [message]);


  useEffect(() => {
    actions[animation]
      .reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);


  useFrame(() => {

    Object.keys(nodes.left_eye.children[0].morphTargetDictionary).forEach((key) => {
      const mapping = facialExpressions[facialExpression];
      if (key === "blink BA") {
        return; // eyes wink/blink are handled separately
      }
      if (mapping && mapping[key]) {
        if (key.startsWith("eye")) {
          lerpMorphTarget(key, mapping[key], 0.1, "eyes");
        }
        else if (key.startsWith("mouth")) {
          lerpMorphTarget(key, mapping[key], 0.1, "head");
        }
        else {
          lerpMorphTarget(key, mapping[key], 0.1);
        }
      } else {
        lerpMorphTarget(key, 0, 0.1);
      }
    });

    lerpMorphTarget("blink BA", blink ? 1 : 0, 0.5, "eyes");

    // LIPSYNC
    if (message && lipsync) {
      const currentAudioTime = audio.currentTime;
      Object.values(lipsyncDefinition).forEach((value) => {
        lerpMorphTarget(value, 0, 1, "head");
      });

      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (currentAudioTime >= mouthCue.start && currentAudioTime <= mouthCue.end) {
          lerpMorphTarget(lipsyncDefinition[mouthCue.value], 1, 1, "head");
          break;
        }
      }
    }
  });

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);


  const lerpMorphTarget = (target, value, speed = 0.1, specificPart = null) => {
    // Funktion für spezifische Teile des Modells, wenn bekannt
    const applyToSpecificPart = (node, childIndices) => {
      if (!node) return;

      // Für jedes angegebene Child-Element
      childIndices.forEach(childIndex => {
        if (node.children && node.children[childIndex]) {
          const child = node.children[childIndex];

          // Prüfe, ob das Child das Morph-Target enthält
          if (child.morphTargetDictionary && child.morphTargetInfluences) {
            const index = child.morphTargetDictionary[target];
            if (index !== undefined && child.morphTargetInfluences[index] !== undefined) {
              child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
                child.morphTargetInfluences[index],
                value,
                speed
              );
            }
          }
        }
      });
    };

    if (specificPart === 'left_eye') {
      applyToSpecificPart(nodes.left_eye, [0, 1, 2]);
      return;
    } else if (specificPart === 'right_eye') {
      applyToSpecificPart(nodes.right_eye, [0, 1, 2]);
      return;
    } else if (specificPart === 'head') {
      applyToSpecificPart(nodes.head, [0, 1, 2]);
      return;
    } else if (specificPart === 'eyes') {
      applyToSpecificPart(nodes.left_eye, [0, 1, 2]);
      applyToSpecificPart(nodes.right_eye, [0, 1, 2]);
      return;
    }

    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );
      }
    });

    // Children von bekannten Knoten direkt behandeln
    if (nodes.left_eye) {
      [0, 1, 2].forEach(i => {
        if (nodes.left_eye.children && nodes.left_eye.children[i]) {
          const child = nodes.left_eye.children[i];
          if (child.morphTargetDictionary && child.morphTargetInfluences) {
            const index = child.morphTargetDictionary[target];
            if (index !== undefined && child.morphTargetInfluences[index] !== undefined) {
              child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
                child.morphTargetInfluences[index],
                value,
                speed
              );
            }
          }
        }
      });
    }

    if (nodes.right_eye) {
      [0, 1, 2].forEach(i => {
        if (nodes.right_eye.children && nodes.right_eye.children[i]) {
          const child = nodes.right_eye.children[i];
          if (child.morphTargetDictionary && child.morphTargetInfluences) {
            const index = child.morphTargetDictionary[target];
            if (index !== undefined && child.morphTargetInfluences[index] !== undefined) {
              child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
                child.morphTargetInfluences[index],
                value,
                speed
              );
            }
          }
        }
      });
    }

    if (nodes.head) {
      [0, 1, 2].forEach(i => {
        if (nodes.head.children && nodes.head.children[i]) {
          const child = nodes.head.children[i];
          if (child.morphTargetDictionary && child.morphTargetInfluences) {
            const index = child.morphTargetDictionary[target];
            if (index !== undefined && child.morphTargetInfluences[index] !== undefined) {
              child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
                child.morphTargetInfluences[index],
                value,
                speed
              );
            }
          }
        }
      });
    }

    try {
      set({
        [target]: value,
      });
    } catch (e) { }
  };



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig001" position={[0, 0, -4]} scale={0.641}>
          <skinnedMesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials['Material.009']}
            skeleton={nodes.body.skeleton}
            morphTargetDictionary={[nodes.head.children[0].morphTargetDictionary, nodes.left_eye.children[0].morphTargetDictionary, nodes.right_eye.morphTargetDictionary, nodes.left_eyebrow.morphTargetDictionary, nodes.right_eyebrow.morphTargetDictionary]}
            morphTargetInfluences={[nodes.head.children[0].morphInfluences, nodes.left_eye.children[0].morphInfluences, nodes.right_eye.morphInfluences, nodes.left_eye.morphInfluences, nodes.right_eyebrow.morphInfluences]}
          />
          <group name="feet">
            <skinnedMesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials['Material.009']}
              skeleton={nodes.Cube001.skeleton}
            />
            <skinnedMesh
              name="Cube001_1"
              geometry={nodes.Cube001_1.geometry}
              material={materials['Material.007']}
              skeleton={nodes.Cube001_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="hands"
            geometry={nodes.hands.geometry}
            material={materials['Material.009']}
            skeleton={nodes.hands.skeleton}
          />
          <skinnedMesh
            name="hip"
            geometry={nodes.hip.geometry}
            material={materials['Material.008']}
            skeleton={nodes.hip.skeleton}
          />
          <skinnedMesh
            name="index_fingers"
            geometry={nodes.index_fingers.geometry}
            material={materials['Material.008']}
            skeleton={nodes.index_fingers.skeleton}
          />
          <skinnedMesh
            name="knees"
            geometry={nodes.knees.geometry}
            material={materials['Material.008']}
            skeleton={nodes.knees.skeleton}
          />
          <skinnedMesh
            name="lower_arms"
            geometry={nodes.lower_arms.geometry}
            material={materials['Material.009']}
            skeleton={nodes.lower_arms.skeleton}
          />
          <skinnedMesh
            name="middle_fingers"
            geometry={nodes.middle_fingers.geometry}
            material={materials['Material.008']}
            skeleton={nodes.middle_fingers.skeleton}
          />
          <skinnedMesh
            name="neck"
            geometry={nodes.neck.geometry}
            material={materials['Material.004']}
            skeleton={nodes.neck.skeleton}
          />
          <skinnedMesh
            name="pinkies"
            geometry={nodes.pinkies.geometry}
            material={materials['Material.008']}
            skeleton={nodes.pinkies.skeleton}
          />
          <skinnedMesh
            name="ring_fingers"
            geometry={nodes.ring_fingers.geometry}
            material={materials['Material.008']}
            skeleton={nodes.ring_fingers.skeleton}
          />
          <skinnedMesh
            name="shoulders"
            geometry={nodes.shoulders.geometry}
            material={materials['Material.008']}
            skeleton={nodes.shoulders.skeleton}
          />
          <skinnedMesh
            name="thighs_joint"
            geometry={nodes.thighs_joint.geometry}
            material={materials['Material.008']}
            skeleton={nodes.thighs_joint.skeleton}
          />
          <skinnedMesh
            name="thumbs"
            geometry={nodes.thumbs.geometry}
            material={materials['Material.008']}
            skeleton={nodes.thumbs.skeleton}
          />
          <skinnedMesh
            name="upper_arms"
            geometry={nodes.upper_arms.geometry}
            material={materials['Material.008']}
            skeleton={nodes.upper_arms.skeleton}
          />
          <primitive object={nodes.spine} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/talkywalky.glb");
