/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState, useMemo } from "react";


import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "A",
  B: "B",
  C: "C",
  D: "D",
  E: "E",
  F: "F",
  G: "A",
  H: "A",
  X: "X"
};

const SYMBOLS = {
  HEART: "heart",
  STAR: "star",
  EXCLAMATION: "exclamation",
  LIGHT_BULB: "lightBulb",
  SMILE: "smile"
};

let setupMode = false;

export function Avatar(props) {
  const group = useRef();

  const { nodes, materials, scene, animations } = useGLTF(
    "/models/talky_walky_2.glb"
  );

  //const { animations } = useGLTF("/models/animations.glb");

  const { actions, mixer } = useAnimations(animations, group);
  //const { actions, mixer } = useAnimations(animations, group);

  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "new idle by jasmin") ? "new idle by jasmin" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );

  console.log(animations)

  const { message, onMessagePlayed, chat } = useChat();

  const [lipsync, setLipsync] = useState();


  // Generische State für Popup-Effekte
  const [popupEffect, setPopupEffect] = useState({
    show: false,
    symbolType: null,
    position: [0, 3, -15],
    count: Math.floor(Math.random() * 3) + 3
  });

  // Funktion zum Auslösen von Popup-Effekten
  const triggerPopupEffect = (symbolType, position = [0, 8, -35], count = Math.floor(Math.random() * 3) + 3) => {
    setPopupEffect({
      show: true,
      symbolType,
      position,
      count
    });

    // Effekt nach kurzem Moment zurücksetzen (der Effekt selbst bleibt noch sichtbar)
    setTimeout(() => {
      setPopupEffect(prev => ({ ...prev, show: false }));
    }, 100);
  };

  useEffect(() => {
    console.log(message);

    if (!message) {
      setAnimation("new idle by jasmin");
      return;
    }
    //setAnimation(message.animation);
    //setFacialExpression(message.facialExpression);
    const text = message.text.toLowerCase();

    // Beispiel für Symbol-Auswahl basierend auf Text
    // Das kann später von OpenAI übernommen werden
    console.log(text);
    if (text.includes("danke") || text.includes("liebe")) {
      triggerPopupEffect(SYMBOLS.HEART);
    }
    else if (text.includes("toll")) {
      triggerPopupEffect(SYMBOLS.STAR, undefined, Math.floor(Math.random() * (15 - 7 + 1)) + 7);
    }
    else if (text.includes("important") || text.includes("achtung")) {
      triggerPopupEffect(SYMBOLS.EXCLAMATION);
    }
    else if (text.includes("idea") || text.includes("verstehe")) {
      triggerPopupEffect(SYMBOLS.LIGHT_BULB);
    }
    else if (text.includes("funny")) {
      triggerPopupEffect(SYMBOLS.SMILE);
    }

    setLipsync(message.lipsync);
    const audio = new Audio("data:audio/mp3;base64," + message.audio);
    console.log("audio:" + audio);
    audio.play();
    setAudio(audio);
    audio.onended = onMessagePlayed;
  }, [message]);

  useEffect(() => {
    actions[animation]
      .reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);


  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) { }
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();


  useFrame(() => {
    /*

    !setupMode &&
      Object.keys(nodes.left_eye.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    */

    nodes.left_eye.morphTargetInfluences[nodes.left_eye.morphTargetDictionary["smile"]] = 0;
    nodes.left_eye.morphTargetInfluences[nodes.left_eye.morphTargetDictionary["happy"]] = 0;
    nodes.left_eye.morphTargetInfluences[nodes.left_eye.morphTargetDictionary["heart"]] = 0;
    nodes.left_eye.morphTargetInfluences[nodes.left_eye.morphTargetDictionary["sad"]] = 0;
    nodes.left_eye.morphTargetInfluences[nodes.left_eye.morphTargetDictionary["star"]] = 0;

    // LIPSYNC
    if (setupMode) {
      return;
    }

    if (message && lipsync) {
      const currentAudioTime = audio.currentTime;

      Object.values(corresponding).forEach((value) => {

        nodes.Head.morphTargetInfluences[nodes.Head.morphTargetDictionary[value]] = 0;

      });

      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (currentAudioTime >= mouthCue.start && currentAudioTime <= mouthCue.end) {
          nodes.Head.morphTargetInfluences[nodes.Head.morphTargetDictionary[corresponding[mouthCue.value]]] = 1;
          break;
        }
      }
    }
  });


  /*
  
  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
          nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });
  
  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );
  
  
  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);
  
  */

  // Öffentliche API-Funktion für externe Aufrufe (z.B. vom Chat-System)
  // Kann später von OpenAI aufgerufen werden
  //props.triggerEffect = triggerPopupEffect;

  return (
    <group {...props} dispose={null} ref={group}>
      <group position={[0, 0.5, -5]} scale={0.641}>
        <primitive object={nodes.spine} />
        <skinnedMesh geometry={nodes.Body.geometry} material={materials.Material_0} skeleton={nodes.Body.skeleton}
          morphTargetDictionary={[nodes.Head.morphTargetDictionary, nodes.left_eye.morphTargetDictionary, nodes.right_eye.morphTargetDictionary, nodes.left_eyebrow.morphTargetDictionary, nodes.right_eyebrow.morphTargetDictionary]}
          morphTargetInfluences={[nodes.Head.morphInfluences, nodes.left_eye.morphInfluences, nodes.right_eye.morphInfluences, nodes.left_eye.morphInfluences, nodes.right_eyebrow.morphInfluences]} />
      </group>
      {/* Generischer Popup-Effekt */}
      <PopupEffect
        symbolType={popupEffect.symbolType}
        trigger={popupEffect.show}
        position={popupEffect.position}
        count={popupEffect.count}
      />
    </group>
  );
}

useGLTF.preload("/models/talky_walky_2.glb");
useGLTF.preload("/models/animations.glb");


// Generische Funktion zum Erstellen der Symbole
function createSymbolShape(symbolType) {
  const shape = new THREE.Shape();

  switch (symbolType) {
    case SYMBOLS.HEART:
      // Herz
      shape.moveTo(0, 0);
      shape.bezierCurveTo(0, -0.5, -1, -1, -2, 0);
      shape.bezierCurveTo(-3, 1, -3, 2, 0, 3.5);
      shape.bezierCurveTo(3, 2, 3, 1, 2, 0);
      shape.bezierCurveTo(1, -1, 0, -0.5, 0, 0);
      return { shape, color: 0xff69b4 }; // Pink

    case SYMBOLS.STAR:
      // Stern
      const points = 5;
      const outerRadius = 1;
      const innerRadius = 0.4;
      const angleStep = Math.PI / points;

      for (let i = 0; i < points * 2; i++) {
        const radius = i % 2 === 0 ? outerRadius : innerRadius;
        const angle = i * angleStep;
        const x = Math.sin(angle) * radius;
        const y = Math.cos(angle) * radius;

        if (i === 0) shape.moveTo(x, y);
        else shape.lineTo(x, y);
      }
      shape.closePath();
      return { shape, color: 0xffff00 }; // Gelb


    case SYMBOLS.EXCLAMATION:
      // Ausrufezeichen
      shape.moveTo(-0.2, 0);
      shape.lineTo(0.2, 0);
      shape.lineTo(0.5, -3);
      shape.lineTo(-0.5, -3);
      shape.closePath();

      // Punkt unter dem Ausrufezeichen
      const dot = new THREE.Shape();
      dot.moveTo(0, 0);
      dot.arc(0, 1.5, 0.4, 0, Math.PI * 2, false);
      dot.closePath();

      return { shape, color: 0xff0000, additionalShapes: [dot] }; // Rot


    case SYMBOLS.LIGHT_BULB:
      // Glühbirne
      shape.moveTo(0, 0);
      shape.arc(0, 0, 1, 0, Math.PI * 2, false);
      shape.moveTo(-0.5, -1);
      shape.lineTo(-0.5, -2);
      shape.lineTo(0.5, -2);
      shape.lineTo(0.5, -1);
      shape.closePath();

      const dotL = new THREE.Shape();
      dotL.moveTo(-0.25, -1);
      dotL.lineTo(-0.25, 0);
      dotL.lineTo(0.25, 0);
      dotL.lineTo(0.25, -1);
      dotL.lineTo(-0.25, -1);
      dotL.closePath();

      return { shape, color: 0xffcc00, additionalShapes: [dotL], additionalColor: 0x888888 }; // Gelb

    case SYMBOLS.SMILE:
      // Smiley
      shape.moveTo(0, 0);
      shape.arc(0, 0, 2, 0, Math.PI * 2, false);
      shape.closePath();

      // Augen
      const leftEye = new THREE.Shape();
      leftEye.moveTo(0, 0);
      leftEye.arc(-0.6, -0.6, 0.3, 0, Math.PI * 2, false);
      leftEye.closePath();

      const rightEye = new THREE.Shape();
      rightEye.moveTo(0, 0);
      rightEye.arc(0.6, -0.6, 0.3, 0, Math.PI * 2, false);
      rightEye.closePath();

      // Mund
      const mouth = new THREE.Shape();
      mouth.moveTo(-1, 0.5);
      mouth.bezierCurveTo(-1, 1.5, 1, 1.5, 1, 0.5);
      mouth.closePath();

      return {
        shape,
        color: 0xffff00,
        additionalShapes: [leftEye, rightEye, mouth],
        additionalColor: 0x000000 // Schwarz für Augen und Mund 
      };

    default:
      // Fallback: einfacher Kreis
      shape.moveTo(0, 0);
      shape.arc(0, 0, 1, 0, Math.PI * 2, false);
      return { shape, color: 0x00ff00 }; // Grün
  }
}

// Generische Symbol-Komponente
function SymbolMesh({ symbolType, position, rotation, scale }) {
  const { shape, color, additionalShapes = [], additionalColor } = createSymbolShape(symbolType);

  return (
    <group position={position} rotation={rotation} scale={scale || 0.2}>
      <mesh>
        <shapeGeometry args={[shape]} />
        <meshBasicMaterial
          color={color}
          side={THREE.DoubleSide}
          transparent
          opacity={1}
        />
      </mesh>

      {/* Zusätzliche Formen rendern (für komplexe Symbole) */}
      {additionalShapes.map((additionalShape, index) => (
        <mesh key={index} renderOrder={1}>
          <shapeGeometry args={[additionalShape]} />
          <meshBasicMaterial
            color={additionalColor !== undefined ? additionalColor : color}
            side={THREE.DoubleSide}
            transparent
            opacity={1}
          />
        </mesh>
      ))}
    </group>
  );
}

// Generische PopupEffect-Komponente
function PopupEffect({ symbolType, trigger, position, count = 5 }) {
  const [effects, setEffects] = useState([]);
  const groupRef = useRef();

  // Beim Auslösen eines Triggers neue Effekte hinzufügen
  useEffect(() => {
    if (trigger) {
      const newEffects = [];
      const effectCount = count || Math.floor(Math.random() * 3) + 3; // 3 bis 5 Symbole

      for (let i = 0; i < effectCount; i++) {
        const randomX = (Math.random() - 0.5) * (5 + Math.random() * 3);
        const randomY = (Math.random() - 0.5) * (1 + Math.random() * 2);
        const delay = Math.random() * 500;

        const effect = {
          id: Date.now() + Math.random(),
          position: [position[0] + randomX, position[1] + randomY, position[2]],
          scale: 0.2 + Math.random() * 0.1,
          rotation: [0, 0, (Math.random() - 0.5) * 0.5],
          opacity: 1
        };

        // Jeder Effekt bekommt sein eigenes Delay
        setTimeout(() => {
          setEffects(prev => [...prev, effect]);

          // Nach 3 Sekunden wieder entfernen
          setTimeout(() => {
            setEffects(prev => prev.filter(e => e.id !== effect.id));
          }, 3000);
        }, delay);
      }
    }
  }, [trigger, position, count]);

  // Animation der Effekte
  useFrame(() => {
    if (groupRef.current && effects.length > 0) {
      // Update effects state with new positions and opacities
      setEffects(prev => prev.map(effect => {
        return {
          ...effect,
          position: [effect.position[0], effect.position[1] + 0.01, effect.position[2]],
          opacity: Math.max(0, effect.opacity - 0.005)
        };
      }));
    }
  });

  return (
    <group ref={groupRef}>
      {effects.map((effect) => (
        <SymbolMesh
          key={effect.id}
          symbolType={symbolType}
          position={effect.position}
          rotation={[effect.rotation[0], effect.rotation[1], effect.rotation[2] + Math.PI]}
          scale={effect.scale}
        />
      ))}
    </group>
  );
}